home/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import re_path
from .view import Annotate

app_name = 'wagtail_review'

urlpatterns = [
    re_path(r'^api/annotations/<int:page_id>$', Annotate.as_view(), name='annotations'),
]

wagtail_review/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from wagtail_review.views import frontend, annotations_api

app_name = 'wagtail_review'

urlpatterns = [
    url(r'^view/(\d+)/(\w+)/$', frontend.view, name='view'),
    url(r'^respond/(\d+)/(\w+)/$', frontend.respond, name='respond'),
    url(r'^api/$', annotations_api.root, name='annotations_api_root'),
    url(r'^api/search/$', annotations_api.search, name='annotations_api_search'),
    url(r'^api/annotations/$', annotations_api.index, name='annotations_api_index'),
    url(r'^api/annotations/(\d+)/$', annotations_api.item, name='annotations_api_item'),
]

wagtail_review/models.py
import random
import string

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Case, Value, When
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _


from wagtail.admin.mail import send_mail  # Wagtail >= 2.7

from wagtail.core.models import UserPagePermissionsProxy

from wagtail_review.text import user_display_name



REVIEW_STATUS_CHOICES = [
    ('open', _("Open")),
    ('closed', _("Closed")),
]


class BaseReview(models.Model):
    """
    Abstract base class for Review models. Can be subclassed to specify application-specific fields, e.g. review type
    """
    page_revision = models.ForeignKey('wagtailcore.PageRevision', related_name='+', on_delete=models.CASCADE, editable=False)
    status = models.CharField(max_length=30, default='open', choices=REVIEW_STATUS_CHOICES, editable=False)
    submitter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='+', editable=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def send_request_emails(self):
        # send request emails to all reviewers except the reviewer record for the user submitting the request
        for reviewer in self.reviewers.exclude(user=self.submitter):
            reviewer.send_request_email()

    @cached_property
    def revision_as_page(self):
        return self.page_revision.as_page_object()

    def get_annotations(self):
        return Annotation.objects.filter(reviewer__review=self).prefetch_related('ranges')

    def get_responses(self):
        return Response.objects.filter(reviewer__review=self).order_by('created_at').select_related('reviewer')

    def get_non_responding_reviewers(self):
        return self.reviewers.filter(responses__isnull=True).exclude(user=self.submitter)

    @classmethod
    def get_pages_with_reviews_for_user(cls, user):
        """
        Return a queryset of pages which have reviews, for which the user has edit permission
        """
        user_perms = UserPagePermissionsProxy(user)
        reviewed_pages = (
            cls.objects
            .order_by('-created_at')
            .values_list('page_revision__page_id', 'created_at')
        )
        # Annotate datetime when a review was last created for this page
        last_review_requested_at = Case(
            *[
                When(pk=pk, then=Value(created_at))
                for pk, created_at in reviewed_pages
            ],
            output_field=models.DateTimeField(),
        )
        return (
            user_perms.editable_pages()
            .filter(pk__in=(page[0] for page in reviewed_pages))
            .annotate(last_review_requested_at=last_review_requested_at)
            .order_by('-last_review_requested_at')
        )

    class Meta:
        abstract = True


class Review(BaseReview):
    pass

def generate_token():
    return ''.join(random.SystemRandom().choice(string.ascii_lowercase + string.digits) for _ in range(16))


class Reviewer(models.Model):
    review = models.ForeignKey(Review, related_name='reviewers', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE, related_name='+')
    email = models.EmailField(blank=True)
    response_token = models.CharField(
        max_length=32, editable=False,
        help_text="Secret token this user must supply to be allowed to respond to the review"
    )
    view_token = models.CharField(
        max_length=32, editable=False,
        help_text="Secret token this user must supply to be allowed to view the page revision being reviewed"
    )

    def clean(self):
        if self.user is None and not self.email:
            raise ValidationError("A reviewer must have either an email address or a user account")

    def get_email_address(self):
        return self.email or self.user.email

    def get_name(self):
        return user_display_name(self.user) if self.user else self.email

    def save(self, **kwargs):
        if not self.response_token:
            self.response_token = generate_token()
        if not self.view_token:
            self.view_token = generate_token()

        super().save(**kwargs)

    def get_respond_url(self, absolute=False):
        url = reverse('wagtail_review:respond', args=[self.id, self.response_token])
        if absolute:
            url = settings.BASE_URL + url
        return url

    def get_view_url(self, absolute=False):
        url = reverse('wagtail_review:view', args=[self.id, self.view_token])
        if absolute:
            url = settings.BASE_URL + url
        return url

    def send_request_email(self):
        if not settings.REVIEW_SEND_EMAIL:
            return
        email_address = self.get_email_address()

        context = {
            'email': email_address,
            'user': self.user,
            'review': self.review,
            'page': self.review.revision_as_page,
            'submitter': self.review.submitter,
            'respond_url': self.get_respond_url(absolute=True),
            'view_url': self.get_view_url(absolute=True),
        }

        email_subject = render_to_string('wagtail_review/email/request_review_subject.txt', context).strip()
        email_content = render_to_string('wagtail_review/email/request_review.txt', context).strip()

        send_mail(email_subject, email_content, [email_address])


class Annotation(models.Model):
    reviewer = models.ForeignKey(Reviewer, related_name='annotations', on_delete=models.CASCADE)
    quote = models.TextField(blank=True)
    text = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def as_json_data(self):
        return {
            'id': self.id,
            'annotator_schema_version': 'v1.0',
            'created': self.created_at.isoformat(),
            'updated': self.updated_at.isoformat(),
            'text': self.text,
            'quote': self.quote,
            'user': {
                'id': self.reviewer.id,
                'name': self.reviewer.get_name(),
            },
            'ranges': [r.as_json_data() for r in self.ranges.all()],
        }


class AnnotationRange(models.Model):
    annotation = models.ForeignKey(Annotation, related_name='ranges', on_delete=models.CASCADE)
    start = models.TextField()
    start_offset = models.IntegerField()
    end = models.TextField()
    end_offset = models.IntegerField()

    def as_json_data(self):
        return {
            'start': self.start,
            'startOffset': self.start_offset,
            'end': self.end,
            'endOffset': self.end_offset,
        }


RESULT_CHOICES = (
    ('approve', 'Approved'),
    ('comment', 'Comment'),
)


class Response(models.Model):
    reviewer = models.ForeignKey(Reviewer, related_name='responses', on_delete=models.CASCADE)
    result = models.CharField(choices=RESULT_CHOICES, max_length=10, blank=False, default=None)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def send_notification_to_submitter(self):
        submitter = self.reviewer.review.submitter
        if submitter.email:

            context = {
                'submitter': submitter,
                'reviewer': self.reviewer,
                'review': self.reviewer.review,
                'page': self.reviewer.review.revision_as_page,
                'response': self,
            }

            email_subject = render_to_string('wagtail_review/email/response_received_subject.txt', context).strip()
            email_content = render_to_string('wagtail_review/email/response_received.txt', context).strip()

            send_mail(email_subject, email_content, [submitter.email])

wagtail_review/views/admin.py
from django.contrib.auth import get_user_model
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.http import require_POST
from django.views.generic.detail import DetailView

import swapper

from wagtail import VERSION as WAGTAIL_VERSION
from wagtail.admin import messages
from wagtail.admin.modal_workflow import render_modal_workflow
from wagtail.admin.views import generic

from wagtail_review.forms import get_review_form_class, ReviewerFormSet
from wagtail_review.models import Reviewer
from wagtail_review.text import user_display_name


Review = swapper.load_model('wagtail_review', 'Review')
User = get_user_model()


def create_review(request):
    ReviewForm = get_review_form_class()

    if request.method == 'GET':
        form = ReviewForm(prefix='create_review')
        reviewer_formset = ReviewerFormSet(prefix='create_review_reviewers')
    else:
        form = ReviewForm(request.POST, prefix='create_review')
        reviewer_formset = ReviewerFormSet(request.POST, prefix='create_review_reviewers')

        form_is_valid = form.is_valid()
        reviewer_formset_is_valid = reviewer_formset.is_valid()

        if not (form_is_valid and reviewer_formset_is_valid):
            return render_modal_workflow(
                request, 'wagtail_review/create_review.html', None, {
                    'form': form,
                    'reviewer_formset': reviewer_formset,
                }, json_data={'step': 'form'}
            )
        else:
            return render_modal_workflow(
                request, None, None, {}, json_data={'step': 'done'}
            )

    return render_modal_workflow(
        request, 'wagtail_review/create_review.html', None, {
            'form': form,
            'reviewer_formset': reviewer_formset,
        }, json_data={'step': 'form'}
    )


def autocomplete_users(request):
    q = request.GET.get('q', '')

    terms = q.split()
    if terms:
        conditions = Q()

        model_fields = [f.name for f in User._meta.get_fields()]

        for term in terms:
            if 'username' in model_fields:
                conditions |= Q(username__icontains=term)

            if 'first_name' in model_fields:
                conditions |= Q(first_name__icontains=term)

            if 'last_name' in model_fields:
                conditions |= Q(last_name__icontains=term)

            if 'email' in model_fields:
                conditions |= Q(email__icontains=term)

        users = User.objects.filter(conditions)
    else:
        users = User.objects.none()

    result_data = [
        {
            'id': user.pk,
            'full_name': user_display_name(user),
            'username': user.get_username(),
        }
        for user in users
    ]

    return JsonResponse({'results': result_data})


class DashboardView(generic.IndexView):
    template_name = 'wagtail_review/admin/dashboard.html'
    page_title = _("Review dashboard")
    context_object_name = 'pages'

    def get_queryset(self):
        return Review.get_pages_with_reviews_for_user(self.request.user)


class AuditTrailView(DetailView):
    template_name = 'wagtail_review/admin/audit_trail.html'
    page_title = _("Audit trail")
    header_icon = 'doc-empty-inverse'
    context_object_name = 'page'

    def get_queryset(self):
        return Review.get_pages_with_reviews_for_user(self.request.user)

    def get_object(self):
        return super().get_object().specific

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['reviews'] = Review.objects.filter(
            page_revision__page=self.object
        ).order_by('created_at').select_related('submitter').prefetch_related('reviewers__responses')
        context['page_permissions'] = self.object.permissions_for_user(self.request.user)

        return context


def view_review_page(request, review_id=None):
    review = get_object_or_404(Review, id=review_id)

    # find a reviewer record corresponding to the current user
    # (the submitter of the review should always have one)
    try:
        reviewer = review.reviewers.get(user=request.user)
    except Reviewer.DoesNotExist:
        # current user is not participating in the review;
        # if they have edit access to the page, give them the submitter's
        # read-only credentials so that they can see annotations

        page = review.page_revision.as_page_object()
        perms = page.permissions_for_user(request.user)

        if not (perms.can_edit() or perms.can_publish()):
            raise PermissionDenied

        try:
            reviewer = review.reviewers.get(user=review.submitter)
        except Reviewer.DoesNotExist:
            raise PermissionDenied

    page = review.page_revision.as_page_object()
    if reviewer.user == request.user:
        review_mode = 'comment'
    else:
        review_mode = 'view'

    if WAGTAIL_VERSION < (2, 7):
        dummy_request = page.dummy_request(request)
        dummy_request.wagtailreview_reviewer = reviewer
        dummy_request.wagtailreview_mode = review_mode
        return page.serve_preview(dummy_request, page.default_preview_mode)
    else:
        return page.make_preview_request(
            original_request=request,
            extra_request_attrs={
                'wagtailreview_reviewer': reviewer,
                'wagtailreview_mode': review_mode,
            }
        )


@require_POST
def close_review(request, review_id=None):
    review = get_object_or_404(Review, id=review_id)
    page = review.page_revision.as_page_object()
    perms = page.permissions_for_user(request.user)

    if not (perms.can_edit() or perms.can_publish()):
        raise PermissionDenied

    review.status = 'closed'
    review.save()

    messages.success(request, _("The review has been closed."))

    return redirect('wagtail_review_admin:audit_trail', page.id)


@require_POST
def close_and_publish(request, review_id=None):
    review = get_object_or_404(Review, id=review_id)
    page = review.page_revision.as_page_object()
    perms = page.permissions_for_user(request.user)
    if not perms.can_publish():
        raise PermissionDenied

    review.status = 'closed'
    review.save()
    review.page_revision.publish()

    messages.success(request, _("The review has been closed and the page published."))

    return redirect('wagtail_review_admin:audit_trail', page.id)


@require_POST
def reopen_review(request, review_id=None):
    review = get_object_or_404(Review, id=review_id)
    page = review.page_revision.as_page_object()
    perms = page.permissions_for_user(request.user)

    if not (perms.can_edit() or perms.can_publish()):
        raise PermissionDenied

    review.status = 'open'
    review.save()

    messages.success(request, _("The review has been reopened."))

    return redirect('wagtail_review_admin:audit_trail', page.id)

wagtail_review/templates/wagtail_review/annotate.html
{% load static %}

{% if mode %}
    <link rel="stylesheet" href="{% static 'wagtailadmin/css/userbar.css' %}">
    <link rel="stylesheet" href="{% static 'wagtail_review/css/annotator.css' %}">
    <link rel="stylesheet" href="{% static 'wagtail_review/css/respond.css' %}">
    <script src="{% static 'wagtail_review/js/annotator-2.0.0a3.min.js' %}"></script>
    <script src="{% static 'wagtail_review/js/annotator-extensions.js' %}"></script>

    {% if allow_responses %}
        <div class="wagtailreview-respond">
            <a href="#" class="js-show-submit" id="wagtailreview-respond-button">
                <span>Submit your review</span>
                <span class="wagtail-icon wagtail-icon-wagtail"></span>
            </a>
            <form class="wagtailreview-respond-form" id="wagtailreview-respond-form" action="{{ reviewer.get_respond_url }}" method="POST">
                {% csrf_token %}
                {% include "wagtail_review/response_form_fields.html" %}
            </form>
        </div>
    {% elif allow_annotations %}
        {# provide an empty respond form so that we can pull the CSRF token from it #}
        <form id="wagtailreview-respond-form">{% csrf_token %}</form>
    {% elif show_closed %}
        <div class="wagtailreview-respond">
            <span class="button-review-closed">This review is now closed</span>
        </div>
    {% endif %}

    <script>
        var app = new annotator.App();
        {% if allow_annotations %}
            app.include(annotator.ui.main, {
                viewerExtensions: [annotatorExt.viewerWithUsernames]
            });
        {% else %}
            app.include(annotatorExt.viewerModeUi);
        {% endif %}
        app.include(annotator.storage.http, {
            'prefix': "{% url 'wagtail_review:annotations_api_root' %}",
            'urls': {
                create: 'annotations/',
                update: 'annotations/{id}/',
                destroy: 'annotations/{id}/',
                search: 'search/'
            },
            'headers': {
                {% if allow_annotations %}
                    'X-CSRFToken': document.getElementById('wagtailreview-respond-form').csrfmiddlewaretoken.value,
                {% endif %}
                'X-WagtailReview-mode': '{{ mode }}',
                'X-WagtailReview-reviewer': '{{ reviewer.id }}',
                'X-WagtailReview-token': '{{ token }}',
            }
        });
        app.start().then(function () {
            app.annotations.load();
        });

        {% if allow_responses %}
            document.addEventListener('DOMContentLoaded', function() {
                var form = document.getElementById('wagtailreview-respond-form');
                form.style.display = 'none';
                formShown = false;

                var button = document.getElementById('wagtailreview-respond-button');
                button.addEventListener('click', function() {
                    if (formShown) {
                        form.style.display = 'none';
                        this.className = 'js-show-submit';
                        formShown = false;
                    } else {
                        form.style.display = 'block';
                        this.className = 'js-show-submit js-icon-up';
                        formShown = true;
                    }
                    return false;
                });
            });
       {% endif %}
    </script>
{% endif %}

wagtail_review/templates/wagtail_review/create_review.html
{% load i18n wagtailadmin_tags %}
{% trans "Submit for review" as title_str %}
{% include "wagtailadmin/shared/header.html" with title=title_str icon='doc-empty-inverse' %}

<div class="nice-padding">
    <form action="{% url 'wagtail_review_admin:create_review' %}" method="POST">
        {% csrf_token %}
        <ul class="fields">
            {% for field in form %}
                {% if field.is_hidden %}
                    {{ field }}
                {% else %}
                    {% include "wagtailadmin/shared/field_as_li.html" with field=field %}
                {% endif %}
            {% endfor %}

            <li class="required">
                <div class="field char_field text_input">
                    <label for="id_create_review-reviewer_autocomplete">Проверяющие:</label>
                    <div class="field-content">
                        {% for err in reviewer_formset.non_form_errors %}
                            <p class="error-message"><span>{{ err }}</span></p>
                        {% endfor %}
                        <div class="input">
                            <input type="text" id="id_create_review-reviewer_autocomplete" class="reviewer-autocomplete" data-autocomplete-url="{% url 'wagtail_review_admin:autocomplete_users' %}">
                            <button type="button" class="button text-replace icon icon-plus" id="id_create_review-reviewer_autocomplete_add" class="reviewer-add">Добавить проверяющиго</button>
                        </div>
                        <p class="help">Введите имя пользователя или адрес электронной почты</p>

                        {{ reviewer_formset.management_form }}
                        <ul class="wagtailreview-reviewer-list" id="id_create_review-reviewer_form_container">
                        </ul>
                    </div>
                </div>
                <script type="text/django-form-template" id="id_{{ reviewer_formset.prefix }}-EMPTY_FORM_TEMPLATE">
                    {% escapescript %}
                        <li>
                            <span id="id_create_review_reviewers-__prefix__-label"></span> <a href="#" class="icon icon-cross" id="id_create_review_reviewers-__prefix__-delete_link"><a/>
                            {{ reviewer_formset.empty_form }}
                        </li>
                    {% endescapescript %}
                </script>
            </li>

            <li><input type="submit" value="{% trans 'Start review' %}" class="button" /></li>
        </ul>
    </form>
</div>

wagtail_review/templates/wagtail_review/response_form_fields.html
<fieldset>
    <legend>Ваша проверка</legend>

    <div class="wagtailreview-respond-form__radios">
        {% for radio in response_form.result %}
            {{ radio }}
        {% endfor %}
    </div>

    <div class="wagtailreview-respond-form__comment">
        <label for="id_comment">Оставить комментарий</label>
        {{ response_form.comment }}
    </div>

    <div class="wagtailreview-respond-form__submit">
        <input type="submit" value="Отправить" id="submit" />
    </div>
</fieldset>

wagtail_review/templates/wagtail_review/submit_for_review_menu_item.html
{% load wagtailadmin_tags %}
<button type="button" name="{{ name }}" value="{{ label }}" class="button" data-url="{% url 'wagtail_review_admin:create_review' %}">{% if icon_name %}{% icon name=icon_name %}{% endif %}{{ label }}</button>